#logging:
#  level:
#    org.hibernate.sql: debug   # log file로 남겨줄수있다.
#    org.hibernate.type: trace  # 쿼리의 파라메터를 보여주는 기능


decorator:
  datasource:
    p6spy:
      enable-logging: true


spring:
  h2:
    console:
      enabled: true         # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console     # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver    # Database? H2? ?????.
    url: jdbc:h2:tcp://localhost/~/development/db/jpa                 # H2 ?? ??
    username: sa                        # H2 ?? ? ??? username ?? (??? ??? ??)
    password:                           # H2 ?? ? ??? password ?? (??? ??? ??)

  jpa:
    open-in-view: false   # 영속성 컨텍스트 내 영속 범위를 Transaction 내에서만 살아있도록 함
#    show-sql: true
    hibernate:
      ddl-auto: create    # Data Definition Language, Application 실행 시 데이터 정의어 옵션
    properties:
      hibernate:
#        format_sql: true
        default_batch_fetch_size: 100 # 배치 조회를 하도록 하는 설정, size에 따라 in절로 조회하는 양이 달라짐


  data:
    web:
      pageable:
        default-page-size: 20   # 페이지 size 전역 설정 | Default size 20
        max-page-size: 100      # 최데 페이지 size | Default size 2000